=== juanmadryn/web-db/trunk/proyectos/trunk/WEB-INF/Xml/datastore.dtd
<?xml encoding="US-ASCII"?>

<!ELEMENT  ResultSet (ResultSetMetaData ,     ResultSetData*)> 

<!ELEMENT  ResultSetMetaData (ColumnMetaData)+> 
<!ELEMENT  ColumnMetaData (Values)*> 
  <!ATTLIST ColumnMetaData 

     	component CDATA #IMPLIED 
     	componentType CDATA #IMPLIED
     	internalName CDATA #IMPLIED 

     	columnName CDATA #REQUIRED
	columnType CDATA #IMPLIED
     	tableName  CDATA #REQUIRED
	schemaName CDATA #IMPLIED
	isbucket (true|false) #IMPLIED

     	nullable (true|false) #IMPLIED
	primaryKey (true|false) #REQUIRED
	updateable (true|false) #IMPLIED

	caption CDATA #IMPLIED
	searchdisplay (true|false) #IMPLIED
	listdisplay (true|false) #IMPLIED
	detaildisplay (true|false) #IMPLIED

	precedence (true|false) #IMPLIED
	exactMatch	(true|false) #IMPLIED
	leadingWildCard CDATA #IMPLIED
	caseSensitive (true|false) #IMPLIED
	mandatory (true|false) #IMPLIED

	locked  (true|false) #IMPLIED
	format CDATA #IMPLIED
	href CDATA #IMPLIED
	advanceSearch (true|false) #IMPLIED
	readonly (true|false) #IMPLIED
	defaultValue CDATA #IMPLIED 
	samerow CDATA #IMPLIED 
	imageFile CDATA #IMPLIED 
	jointo CDATA #IMPLIED
  > 
  <!ELEMENT Values (Option)*>
	<!ATTLIST Values 
		type (Static|Dynamic) #REQUIRED
		component (IntegerDropDown|StringDropDown|StringRadioButtonGroup|IntegerRadioButtonGroup) #REQUIRED
		table CDATA #IMPLIED
		initColumn CDATA #IMPLIED
		descColumn CDATA #IMPLIED
		xmlFileName CDATA #IMPLIED
	>
	<!ELEMENT Option EMPTY>
	<!ATTLIST Option
		key CDATA #REQUIRED
		data CDATA #REQUIRED
	>

<!ELEMENT ResultSetData (Row)*> 
<!ELEMENT  Row (Column)+> 
<!ELEMENT Column  EMPTY> 
 <!ATTLIST Column 
		table CDATA #REQUIRED
		name CDATA #REQUIRED
		value CDATA #REQUIRED 
	>

=== juanmadryn/web-db/trunk/proyectos/tags/20071212.0/WEB-INF/Xml/listform.xml
<?xml version="1.0"?>
<!DOCTYPE ResultSet SYSTEM "datastore.dtd">

<ResultSet>
<ResultSetMetaData>

<ColumnMetaData 
      component="caption"
	caption="Caption"
      columnname="caption" 
      tablename="listform"
	columntype="String"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="false"
	updateable="true"
>
</ColumnMetaData>  

<ColumnMetaData 
      	component="internalname"
	caption="Internal Name"
      	columnname="internalname" 
      	tablename="listform"
	columntype="String"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="false"
	updateable="true"
>
</ColumnMetaData>


<ColumnMetaData 
      	component="test"
	caption="Component"
      	columnname="component" 
      	tablename="listform"
	columntype="String"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="false"
	updateable="true"
>
</ColumnMetaData>

<ColumnMetaData 
      	component="componenttype"
	caption="Component Type"
      	columnname="componenttype" 
      	tablename="listform"
	columntype="String"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
 	samerow="true"
	updateable="true"
>
<Values type="Static" component="StringDropDown" xmlfilename="componentTypes.xml">
</Values>
</ColumnMetaData>

<ColumnMetaData 
      	component="schemaname"
	caption="Schema Name"
      	columnname="schemaname" 
      	tablename="listform"
	columntype="String"
	searchdisplay="true"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="true"
	mandatory="true"
	defaultValue="listform"
	samerow="false"
	updateable="true"
>
</ColumnMetaData>   

<ColumnMetaData 
      	component="tablenames"
	caption="Table Name"
      	columnname="tablename" 
      	tablename="listform"
	columntype="String"
	searchdisplay="true"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="true"
	mandatory="true"
	defaultValue="listform"
	samerow="false"
	updateable="true"
>
</ColumnMetaData>   


<ColumnMetaData 
      	component="columnnames"
	caption="Column Name"
      	columnname="columnname" 
      	tablename="listform"
	columntype="String"
	searchdisplay="true"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="true"
	mandatory="true"
	samerow="true"
	href="DetailFormUtility.jsp?mode=update"
	updateable="true"
>
</ColumnMetaData>

<ColumnMetaData 
      	component="columntype"
	caption="Column Type"
      	columnname="columntype" 
      	tablename="listform"
	columntype="String"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="true"
	samerow="true"
	updateable="true"
>
</ColumnMetaData>   

<ColumnMetaData 
      	component="Bucket"
	caption="Bucket"
      	columnname="isbucket" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="false"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>  

<ColumnMetaData 
      	component="nullable"
	caption="Nullable"
      	columnname="nullable" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>  

<ColumnMetaData 
      	component="searchdisplay"
	caption="Search Display"
      	columnname="searchdisplay" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="true"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>  

<ColumnMetaData 
      	component="listdisplay"
	caption="List Display"
      	columnname="listdisplay" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="false"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>  

<ColumnMetaData 
      	component="detaildisplay"
	caption="Detail display"
      	columnname="detaildisplay" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="true"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>  

<ColumnMetaData 
      	component="precedence"
	caption="Precedence"
      	columnname="precedence" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>  

<ColumnMetaData 
      	component="exactmatch"
	caption="Exact Match"
      	columnname="exactmatch" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="true"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>  

<ColumnMetaData 
      	component="leadingwildcard"
	caption="Leading WildCard"
      	columnname="leadingwildcard" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>  

<ColumnMetaData 
      	component="caseSensitive"
	caption="Case Senstive"
      	columnname="casesensitive" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="true"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>  

<ColumnMetaData 
      	component="mandatory"
	caption="Mandatory"
      	columnname="mandatory" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="true"
	samerow="false"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData> 

<ColumnMetaData 
      	component="locked"
	caption="Locked"
      	columnname="locked" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="true"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData> 

<ColumnMetaData 
      	component="primarykey"
	caption="Primary Key"
      	columnname="primarykey" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="true"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="true"
	samerow="false"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>   


<ColumnMetaData 
      	component="updateable"
	caption="Updateable"
      	columnname="updateable" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="true"
	samerow="true"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData>   


<ColumnMetaData 
      	component="format"
	caption="Format"
      	columnname="format" 
      	tablename="listform"
	columntype="String"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	updateable="true"
>
</ColumnMetaData> 

<ColumnMetaData 
      	component="href"
	caption="Href Expression"
      	columnname="href" 
      	tablename="listform"
	columntype="String"
	searchdisplay="false"
	listdisplay="true"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	samerow="true"
	updateable="true"
>
</ColumnMetaData> 

<ColumnMetaData 
      	component="readonly"
	caption="Read Only"
      	columnname="readonly" 
      	tablename="listform"
	columntype="Integer"
	searchdisplay="false"
	listdisplay="false"
	detaildisplay="true"
	nullable="false"	
	primarykey="false"
	mandatory="false"
	updateable="true"
>
<Values type="Static" component="IntegerDropDown" xmlfilename="boolean.xml">
</Values>
</ColumnMetaData> 

<ColumnMetaData 
      	component="imageFile"
	caption="Image File Name"
      	columnname="imagefile" 
      	tablename="listform"
	columntype="String"
